# Избранное

## Список избранный предложений

GET http://localhost:5000/favorites HTTP/1.1

###

## Добавить в избранное

POST http://localhost:5000/favorites/672048f4f74eed4cf40b9fc0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7Im5hbWUiOiJNYXgiLCJlbWFpbCI6Imt1am8tZmFuQHN0b3J5LmxvY2FsIiwiaWQiOiI2NzIwNDhmNGY3NGVlZDRjZjQwYjllNGIifSwiaWF0IjoxNzMwMTg1NjYwLCJleHAiOjE3MzAzNTg0NjB9.6wqSvTs_TGD5dYTYOhBok7Uu1eJJUrZCHe5Pt5qRz-I

###

## Удалить из избранного

DELETE http://localhost:5000/favorites/672048f4f74eed4cf40b9fc0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7Im5hbWUiOiJNYXgiLCJlbWFpbCI6Imt1am8tZmFuQHN0b3J5LmxvY2FsIiwiaWQiOiI2NzIwNDhmNGY3NGVlZDRjZjQwYjllNGIifSwiaWF0IjoxNzMwMTg1NjYwLCJleHAiOjE3MzAzNTg0NjB9.6wqSvTs_TGD5dYTYOhBok7Uu1eJJUrZCHe5Pt5qRz-I
