# Предложения
## Создать предложение

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "offer title",
  "publishDate": "2024-07-09T11:24:14.495Z",
  "city": "Paris",
  "previewImage": "preview-img-4.jpg",
  "isPremium": true,
  "type": "room",
  "price": 101,
  "location": {
    "latitude": 10.5,
    "longitude": 11.5
  },
  "description": "offer description offer description",
  "images": [
    "img-11.jpg",
    "img-12.jpg",
    "img-13.jpg",
    "img-14.jpg",
    "img-15.jpg",
    "img-16.jpg"
  ],
  "rooms": 2,
  "maxAdults": 4,
  "goods": [
    "Washer",
    "Breakfast"
  ],
  "hostId": "671ca4813540f0eb196d988b"
}

###

## Список предложений

GET http://localhost:4000/offers HTTP/1.1

###

## Список предложений

GET http://localhost:4000/offers?count=10 HTTP/1.1

###

## Список премиум предложений

GET http://localhost:4000/offers?isPremium=true HTTP/1.1

###

## Предложение

GET http://localhost:4000/offers/671cb25892232b9f591fa8c4 HTTP/1.1

###

## Изменить предложение

PATCH http://localhost:4000/offers/671cb25892232b9f591fa8c4 HTTP/1.1
Content-Type: application/json

{
  "title": "offer title edit",
  "publishDate": "2024-07-09T11:24:14.495Z",
  "city": "Paris",
  "previewImage": "preview-img-4.jpg"
}

###

## Удалить предложение

DELETE http://localhost:4000/offers/671b04f7ce79e9c18a7d0d93 HTTP/1.1

###
